# Generated by Django 4.2.13 on 2024-06-25 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_post_post_kind_usercategory_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(related_name='users', through='news.UserCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
